version: "1.0"
providers:

  thand:
    name: Thand Provider
    description: Thand internal provider
    provider: thand
    enabled: true

  azure:
    name: Azure Cloud Provider
    description: Microsoft Azure cloud provider
    provider: azure
    enabled: true

  email:
    name: Azure Email
    description: Azure SMTP for notifications
    provider: email
    enabled: true