version: "1.0"
providers:

  thand:
    name: Thand Provider
    description: Thand internal provider
    provider: thand
    enabled: true

  kubernetes:
    name: Kubernetes
    description: Kubernetes cluster
    provider: kubernetes
    enabled: true
    config:
      context: default
